name: Analyzing Copilot CLI Thinking (Agentic 🤖)
on:
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read
jobs:
  Analyzing-Copilot-CLI-Thinking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          fetch-depth: 0

      - name: Set up Node.js environment
        uses: actions/setup-node@v4

      - name: Install Copilot CLI
        run: npm install -g @github/copilot

      - name: Download Agent Skills
        run: |
          git clone https://github.com/leslieRD/Agent-Skills.git ./agent/skills/
          echo "Agent skills downloaded to ./agent/skills/skills"
          ls -la ./agent/skills/skills


      - name: Azure CLI Login
        uses: azure/login@v2
        with:
            client-id: ${{ vars.AZURE_CLIENT_ID }}
            tenant-id: ${{ vars.AZURE_TENANT_ID }}
            subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

            
      - name: Run Copilot CLI
        env:
          COPILOT_GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          copilot -p "Deploy a simple storage account in the Azure subscription use in this runner within a resource group named agent-rg" --allow-tool='shell(git:*)' --allow-tool=all --no-ask-user --model=claude-opus-4.7
